version: '2.4'

services:
  dev_nginx:
    container_name: 'dev_nginx_proxy'
    image: nginx:stable
    ports:
      - '8000:80'
    networks:
      - dataverse
    depends_on:
      - dev_dataverse
      - dev_frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./docker-dev-volumes/nginx/logs:/var/log/nginx/

  dev_frontend:
    container_name: 'dev_frontend'
    hostname: frontend
    build:
      context: ../
      dockerfile: ./dev.Dockerfile
      network: host
    expose:
      - '5173'
    stdin_open: true
    networks:
      - dataverse
    depends_on:
      - dev_dataverse
    environment:
      - VITE_DATAVERSE_BACKEND_URL=http://localhost:8000
    volumes:
      - ../:/usr/src/app
      - ../dev-env/vite.config.ts:/usr/src/app/vite.config.ts
      - /usr/src/app/dev-env
      - /usr/src/app/node_modules

  dev_dataverse:
    container_name: 'dev_dataverse'
    hostname: dataverse
    image: ${REGISTRY}/gdcc/dataverse:${DATAVERSE_IMAGE_TAG}
    restart: on-failure
    user: payara
    environment:
      DATAVERSE_DB_HOST: postgres
      DATAVERSE_DB_PASSWORD: secret
      DATAVERSE_DB_USER: ${DATAVERSE_DB_USER}
      DATAVERSE_FEATURE_API_SESSION_AUTH: 1
      JVM_ARGS: -Ddataverse.pid.providers=fake
        -Ddataverse.pid.default-provider=fake
        -Ddataverse.pid.fake.type=FAKE
        -Ddataverse.pid.fake.label=FakeDOIProvider
        -Ddataverse.pid.fake.authority=10.5072
        -Ddataverse.pid.fake.shoulder=FK2/
        -Ddataverse.files.storage-driver-id=localstack1
        -Ddataverse.files.localstack1.type=s3
        -Ddataverse.files.localstack1.label=LocalStack
        -Ddataverse.files.localstack1.custom-endpoint-url=http://localhost:4566
        -Ddataverse.files.localstack1.custom-endpoint-region=us-east-2
        -Ddataverse.files.localstack1.bucket-name=mybucket
        -Ddataverse.files.localstack1.path-style-access=true
        -Ddataverse.files.localstack1.upload-redirect=true
        -Ddataverse.files.localstack1.download-redirect=true
        -Ddataverse.files.localstack1.access-key=default
        -Ddataverse.files.localstack1.secret-key=default
    expose:
      - '8080'
    networks:
      - dataverse
    depends_on:
      - dev_postgres
      - dev_solr
      - dev_localstack
    volumes:
      - ./docker-dev-volumes/app/data:/dv
      - ./docker-dev-volumes/app/secrets:/secrets
    tmpfs:
      - /dumps:mode=770,size=2052M,uid=1000,gid=1000
      - /tmp:mode=770,size=2052M,uid=1000,gid=1000
    mem_limit: 2147483648 # 2 GiB
    mem_reservation: 1024m
    privileged: false

  dv_initializer:
    container_name: 'dv_initializer'
    image: gdcc/configbaker:unstable
    restart: 'no'
    command:
      - sh
      - -c
      - 'fix-fs-perms.sh dv'
    volumes:
      - ./docker-dev-volumes/app/data:/dv

  dev_localstack:
    container_name: 'dev_localstack'
    hostname: 'localstack'
    image: localstack/localstack:2.3.2
    restart: on-failure
    ports:
      - '4566:4566'
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    networks:
      - dataverse
    volumes:
      - ./conf/localstack:/etc/localstack/init/ready.d
    tmpfs:
      - /localstack:mode=770,size=128M,uid=1000,gid=1000

  dev_dataverse_bootstrap:
    container_name: 'dev_dataverse_bootstrap'
    image: gdcc/configbaker:unstable
    restart: 'no'
    environment:
      - TIMEOUT=${DATAVERSE_BOOTSTRAP_TIMEOUT}
    command:
      - bootstrap.sh
      - dev
    networks:
      - dataverse

  dev_postgres:
    container_name: 'dev_postgres'
    hostname: postgres
    image: postgres:${POSTGRES_VERSION}
    restart: on-failure
    environment:
      - POSTGRES_USER=${DATAVERSE_DB_USER}
      - POSTGRES_PASSWORD=secret
    expose:
      - '5432'
    networks:
      - dataverse
    volumes:
      - ./docker-dev-volumes/postgresql/data:/var/lib/postgresql/data

  dev_solr_initializer:
    container_name: 'dev_solr_initializer'
    image: gdcc/configbaker:unstable
    restart: 'no'
    command:
      - sh
      - -c
      - 'fix-fs-perms.sh solr && cp -a /template/* /solr-template'
    volumes:
      - ./docker-dev-volumes/solr/data:/var/solr
      - ./docker-dev-volumes/solr/conf:/solr-template

  dev_solr:
    container_name: 'dev_solr'
    hostname: 'solr'
    image: solr:${SOLR_VERSION}
    depends_on:
      dev_solr_initializer:
        condition: service_completed_successfully
    restart: on-failure
    expose:
      - '8983'
    networks:
      - dataverse
    command:
      - 'solr-precreate'
      - 'collection1'
      - '/template'
    volumes:
      - ./docker-dev-volumes/solr/data:/var/solr
      - ./docker-dev-volumes/solr/conf:/template

  dev_smtp:
    container_name: 'dev_smtp'
    hostname: 'smtp'
    image: maildev/maildev:2.0.5
    restart: on-failure
    expose:
      - '25' # smtp server
    ports:
      - '1080:1080' # web ui
    environment:
      - MAILDEV_SMTP_PORT=25
      - MAILDEV_MAIL_DIRECTORY=/mail
    networks:
      - dataverse
    #volumes:
    #  - ./docker-dev-volumes/smtp/data:/mail
    tmpfs:
      - /mail:mode=770,size=128M,uid=1000,gid=1000

networks:
  dataverse:
    driver: bridge
